language: c

sudo: true

os:
 - linux
 - osx
 
compiler:
 - gcc
 - clang
 
install:
 - git clone --branch=dev https://github.com/tboox/xmake.git tboox/xmake --depth 1
 - cd ./tboox/xmake
 - make build
 - sudo make install
 - cd -

script:
 - xmake
 - sudo xmake install
 - xmake r ldev_test
